### ISSUE TITLE
Back end

### ISSUE THREAD

**Issue by 1uhost** [unixy/varnishtuner.py#4]
Could you improve on the scripts reccomendations? Example, when run we get:
"Backend's weak. Ensure it's optimal (backend_fail: 11"
No clue what the above means or what to adjust to fix it.
unixy varnish cpanel plugin.

**Comment by unixy** [comment]
The backend is the service that Varnish communicates with to fetch objects. In the case of the unixy varnish plugin, that's Apache. The wording definitely needs to change. I'll work on that.

Also, if you re-run the script again and the backend_fail counter keeps increasing, it generally means Apache is throwing errors (ex: 500). Check /usr/local/apache/logs/error_log for clues. However, if it stays at a fixed value (ex: 11), it's likely that Apache restarted and Varnish couldn't communicate with it until it came back up. In this case, you need not be concerned that much.

**Comment by 1uhost** [comment]
It was the word "weak" that threw us:) 
Thanks for the info.
