### ISSUE TITLE
sess_workspace

### ISSUE THREAD

**Issue by 1uhost** [unixy/varnishtuner.py#5]
Am wondering if the scripts sess_workspace suggestion is accurate? The unixy cpanel varnish version has default sess_workspace of 1048576 in all templates but running this tuning scripts has had us doubling up on that figure every 24  hours, its now sugesting:
---- Recommendations -----
Increase sess_workspace ( > 4194304 )
Increase thread_pool_min ( > 300 but < 400)
Is there anything we can check to confirm this increase in sess_workspace is required?
Thanks.

**Comment by unixy** [comment]
Can you post the output of: /usr/local/varnish/bin/varnishstat -1

**Comment by 1uhost** [comment]
Hi,

# /usr/local/varnish/bin/varnishstat -1

client_conn             167923         8.21 Client connections accepted
client_drop                  0         0.00 Connection dropped, no sess/wrk
client_req              220138        10.76 Client requests received
cache_hit                 8745         0.43 Cache hits
cache_hitpass              806         0.04 Cache hits for pass
cache_miss               98658         4.82 Cache misses
backend_conn            114554         5.60 Backend conn. success
backend_unhealthy            0         0.00 Backend conn. not attempted
backend_busy                 0         0.00 Backend conn. too many
backend_fail                 0         0.00 Backend conn. failures
backend_reuse            96838         4.74 Backend conn. reuses
backend_toolate            707         0.03 Backend conn. was closed
backend_recycle          97557         4.77 Backend conn. recycles
backend_retry                5         0.00 Backend conn. retry
fetch_head                   6         0.00 Fetch head
fetch_length             92157         4.51 Fetch with Length
fetch_chunked            10504         0.51 Fetch chunked
fetch_eof                    0         0.00 Fetch EOF
fetch_bad                    0         0.00 Fetch had bad headers
fetch_close                115         0.01 Fetch wanted close
fetch_oldhttp                0         0.00 Fetch pre HTTP/1.1 closed
fetch_zero                   0         0.00 Fetch zero len
fetch_failed                 0         0.00 Fetch failed
fetch_1xx                    0         0.00 Fetch no body (1xx)
fetch_204                    0         0.00 Fetch no body (204)
fetch_304                  119         0.01 Fetch no body (304)
n_sess_mem                 213          .   N struct sess_mem
n_sess                      13          .   N struct sess
n_object                  1825          .   N struct object
n_vampireobject              0          .   N unresurrected objects
n_objectcore              1840          .   N struct objectcore
n_objecthead              2419          .   N struct objecthead
n_waitinglist              178          .   N struct waitinglist
n_vbc                       14          .   N struct vbc
n_wrk                     1050          .   N worker threads
n_wrk_create              1050         0.05 N worker threads created
n_wrk_failed                 0         0.00 N worker threads not created
n_wrk_max                    0         0.00 N worker threads limited
n_wrk_lqueue                 0         0.00 work request queue length
n_wrk_queued                 5         0.00 N queued work requests
n_wrk_drop                   0         0.00 N dropped work requests
n_backend                   19          .   N backends
n_expired                96719          .   N expired objects
n_lru_nuked                  0          .   N LRU nuked objects
n_lru_moved               5610          .   N LRU moved objects
losthdr                      0         0.00 HTTP header overflows
n_objsendfile                0         0.00 Objects sent with sendfile
n_objwrite               99834         4.88 Objects sent with write
n_objoverflow                0         0.00 Objects overflowing workspace
s_sess                  167922         8.21 Total Sessions
s_req                   220138        10.76 Total Requests
s_pipe                  108460         5.30 Total pipe
s_pass                    4267         0.21 Total pass
s_fetch                 102787         5.03 Total fetch
s_hdrbytes            42243305      2065.69 Total header bytes
s_bodybytes         3675908768    179751.04 Total body bytes
sess_closed             123213         6.03 Session Closed
sess_pipeline             1170         0.06 Session Pipeline
sess_readahead              93         0.00 Session Read Ahead
sess_linger              97769         4.78 Session Linger
sess_herd               106033         5.18 Session herd
shm_records           13995668       684.38 SHM records
shm_writes             1176229        57.52 SHM writes
shm_flushes                  0         0.00 SHM flushes due to overflow
shm_cont                  1471         0.07 SHM MTX contention
shm_cycles                   5         0.00 SHM cycles through buffer
sms_nreq                     0         0.00 SMS allocator requests
sms_nobj                     0          .   SMS outstanding allocations
sms_nbytes                   0          .   SMS outstanding bytes
sms_balloc                   0          .   SMS bytes allocated
sms_bfree                    0          .   SMS bytes freed
backend_req             102896         5.03 Backend requests made
n_vcl                        1         0.00 N vcl total
n_vcl_avail                  1         0.00 N vcl available
n_vcl_discard                0         0.00 N vcl discarded
n_ban                        1          .   N total active bans
n_ban_gone                   1          .   N total gone bans
n_ban_add                    1         0.00 N new bans added
n_ban_retire                 0         0.00 N old bans deleted
n_ban_obj_test               0         0.00 N objects tested
n_ban_re_test                0         0.00 N regexps tested against
n_ban_dups                   0         0.00 N duplicate bans removed
hcb_nolock              108198         5.29 HCB Lookups without lock
hcb_lock                 67906         3.32 HCB Lookups with lock
hcb_insert               67905         3.32 HCB Inserts
esi_errors                   0         0.00 ESI parse errors (unlock)
esi_warnings                 0         0.00 ESI parse warnings (unlock)
accept_fail                  0         0.00 Accept failures
client_drop_late             0         0.00 Connection dropped late
uptime                   20450         1.00 Client uptime
dir_dns_lookups              0         0.00 DNS director lookups
dir_dns_failed               0         0.00 DNS director failed lookups
dir_dns_hit                  0         0.00 DNS director cached lookups hit
dir_dns_cache_full           0         0.00 DNS director full dnscache
vmods                        0          .   Loaded VMODs
n_gzip                       0         0.00 Gzip operations
n_gunzip                 19632         0.96 Gunzip operations
sess_pipe_overflow           0          .   Dropped sessions due to session pipe overflow
LCK.sms.creat                1         0.00 Created locks
LCK.sms.destroy              0         0.00 Destroyed locks
LCK.sms.locks                0         0.00 Lock Operations
LCK.sms.colls                0         0.00 Collisions
LCK.smp.creat                0         0.00 Created locks
LCK.smp.destroy              0         0.00 Destroyed locks
LCK.smp.locks                0         0.00 Lock Operations
LCK.smp.colls                0         0.00 Collisions
LCK.sma.creat                1         0.00 Created locks
LCK.sma.destroy              0         0.00 Destroyed locks
LCK.sma.locks            21451         1.05 Lock Operations
LCK.sma.colls                0         0.00 Collisions
LCK.smf.creat                1         0.00 Created locks
LCK.smf.destroy              0         0.00 Destroyed locks
LCK.smf.locks           408489        19.98 Lock Operations
LCK.smf.colls                0         0.00 Collisions
LCK.hsl.creat                0         0.00 Created locks
LCK.hsl.destroy              0         0.00 Destroyed locks
LCK.hsl.locks                0         0.00 Lock Operations
LCK.hsl.colls                0         0.00 Collisions
LCK.hcb.creat                1         0.00 Created locks
LCK.hcb.destroy              0         0.00 Destroyed locks
LCK.hcb.locks           134478         6.58 Lock Operations
LCK.hcb.colls                0         0.00 Collisions
LCK.hcl.creat                0         0.00 Created locks
LCK.hcl.destroy              0         0.00 Destroyed locks
LCK.hcl.locks                0         0.00 Lock Operations
LCK.hcl.colls                0         0.00 Collisions
LCK.vcl.creat                1         0.00 Created locks
LCK.vcl.destroy              0         0.00 Destroyed locks
LCK.vcl.locks              327         0.02 Lock Operations
LCK.vcl.colls                0         0.00 Collisions
LCK.stat.creat               1         0.00 Created locks
LCK.stat.destroy             0         0.00 Destroyed locks
LCK.stat.locks          168124         8.22 Lock Operations
LCK.stat.colls               0         0.00 Collisions
LCK.sessmem.creat            1         0.00 Created locks
LCK.sessmem.destroy            0         0.00 Destroyed locks
LCK.sessmem.locks         169716         8.30 Lock Operations
LCK.sessmem.colls              0         0.00 Collisions
LCK.wstat.creat                1         0.00 Created locks
LCK.wstat.destroy              0         0.00 Destroyed locks
LCK.wstat.locks            41259         2.02 Lock Operations
LCK.wstat.colls                0         0.00 Collisions
LCK.herder.creat               1         0.00 Created locks
LCK.herder.destroy             0         0.00 Destroyed locks
LCK.herder.locks               1         0.00 Lock Operations
LCK.herder.colls               0         0.00 Collisions
LCK.wq.creat                   3         0.00 Created locks
LCK.wq.destroy                 0         0.00 Destroyed locks
LCK.wq.locks              521039        25.48 Lock Operations
LCK.wq.colls                   0         0.00 Collisions
LCK.objhdr.creat           67918         3.32 Created locks
LCK.objhdr.destroy         65540         3.20 Destroyed locks
LCK.objhdr.locks          656950        32.12 Lock Operations
LCK.objhdr.colls               0         0.00 Collisions
LCK.exp.creat                  1         0.00 Created locks
LCK.exp.destroy                0         0.00 Destroyed locks
LCK.exp.locks             215801        10.55 Lock Operations
LCK.exp.colls                  0         0.00 Collisions
LCK.lru.creat                  2         0.00 Created locks
LCK.lru.destroy                0         0.00 Destroyed locks
LCK.lru.locks              98637         4.82 Lock Operations
LCK.lru.colls                  0         0.00 Collisions
LCK.cli.creat                  1         0.00 Created locks
LCK.cli.destroy                0         0.00 Destroyed locks
LCK.cli.locks               6826         0.33 Lock Operations
LCK.cli.colls                  0         0.00 Collisions
LCK.ban.creat                  1         0.00 Created locks
LCK.ban.destroy                0         0.00 Destroyed locks
LCK.ban.locks             215714        10.55 Lock Operations
LCK.ban.colls                  0         0.00 Collisions
LCK.vbp.creat                  1         0.00 Created locks
LCK.vbp.destroy                0         0.00 Destroyed locks
LCK.vbp.locks                  0         0.00 Lock Operations
LCK.vbp.colls                  0         0.00 Collisions
LCK.vbe.creat                  1         0.00 Created locks
LCK.vbe.destroy                0         0.00 Destroyed locks
LCK.vbe.locks             229094        11.20 Lock Operations
LCK.vbe.colls                  0         0.00 Collisions
LCK.backend.creat             19         0.00 Created locks
LCK.backend.destroy            0         0.00 Destroyed locks
LCK.backend.locks         538750        26.34 Lock Operations
LCK.backend.colls              0         0.00 Collisions
SMF.s0.c_req              191501         9.36 Allocator requests
SMF.s0.c_fail                  0         0.00 Allocator failures
SMF.s0.c_bytes        7411019776    362397.06 Bytes allocated
SMF.s0.c_freed        7348011008    359315.94 Bytes freed
SMF.s0.g_alloc              3557          .   Allocations outstanding
SMF.s0.g_bytes          63008768          .   Bytes outstanding
SMF.s0.g_space        1010733056          .   Bytes available
SMF.s0.g_smf                3668          .   N struct smf
SMF.s0.g_smf_frag             94          .   N small free smf
SMF.s0.g_smf_large            17          .   N large free smf
SMA.Transient.c_req        10387         0.51 Allocator requests
SMA.Transient.c_fail           0         0.00 Allocator failures
SMA.Transient.c_bytes    132307967      6469.83 Bytes allocated
SMA.Transient.c_freed    132283967      6468.65 Bytes freed
SMA.Transient.g_alloc           30          .   Allocations outstanding
SMA.Transient.g_bytes        24000          .   Bytes outstanding
SMA.Transient.g_space            0          .   Bytes available
VBE.default(xxx.xxx.106.10,,82).vcls            1          .   VCL references
VBE.default(xxx.xxx.106.10,,82).happy           0          .   Happy health probes
VBE.bexxx.xxx_106_14(xxx.xxx.106.14,,82).vcls            1          .   VCL references
VBE.bexxx.xxx_106_14(xxx.xxx.106.14,,82).happy           0          .   Happy health probes
VBE.bexxx.xxx_106_11(xxx.xxx.106.11,,82).vcls            1          .   VCL references
VBE.bexxx.xxx_106_11(xxx.xxx.106.11,,82).happy           0          .   Happy health probes
VBE.bexxx.xxx_106_10(xxx.xxx.106.10,,82).vcls            1          .   VCL references
VBE.bexxx.xxx_106_10(xxx.xxx.106.10,,82).happy           0          .   Happy health probes
VBE.bexxx.xxx_106_13(xxx.xxx.106.13,,82).vcls            1          .   VCL references
VBE.bexxx.xxx_106_13(xxx.xxx.106.13,,82).happy           0          .   Happy health probes
VBE.bexxx.xxx_106_12(xxx.xxx.106.12,,82).vcls            1          .   VCL references
VBE.bexxx.xxx_106_12(xxx.xxx.106.12,,82).happy           0          .   Happy health probes
VBE.bexxx.xxx_106_70(xxx.xxx.106.70,,82).vcls            1          .   VCL references
VBE.bexxx.xxx_106_70(xxx.xxx.106.70,,82).happy           0          .   Happy health probes
VBE.bexxx.xxx_106_77(xxx.xxx.106.77,,82).vcls            1          .   VCL references
VBE.bexxx.xxx_106_77(xxx.xxx.106.77,,82).happy           0          .   Happy health probes
VBE.bexxx.xxx_106_71(xxx.xxx.106.71,,82).vcls            1          .   VCL references
VBE.bexxx.xxx_106_71(xxx.xxx.106.71,,82).happy           0          .   Happy health probes
VBE.bexxx.xxx_106_75(xxx.xxx.106.75,,82).vcls            1          .   VCL references
VBE.bexxx.xxx_106_75(xxx.xxx.106.75,,82).happy           0          .   Happy health probes
VBE.bexxx.xxx_106_74(xxx.xxx.106.74,,82).vcls            1          .   VCL references
VBE.bexxx.xxx_106_74(xxx.xxx.106.74,,82).happy           0          .   Happy health probes
VBE.bexxx.xxx_106_73(xxx.xxx.106.73,,82).vcls            1          .   VCL references
VBE.bexxx.xxx_106_73(xxx.xxx.106.73,,82).happy           0          .   Happy health probes
VBE.bexxx.xxx_106_72(xxx.xxx.106.72,,82).vcls            1          .   VCL references
VBE.bexxx.xxx_106_72(xxx.xxx.106.72,,82).happy           0          .   Happy health probes
VBE.bexxx.xxx_106_66(xxx.xxx.106.66,,82).vcls            1          .   VCL references
VBE.bexxx.xxx_106_66(xxx.xxx.106.66,,82).happy           0          .   Happy health probes
VBE.bexxx.xxx_106_67(xxx.xxx.106.67,,82).vcls            1          .   VCL references
VBE.bexxx.xxx_106_67(xxx.xxx.106.67,,82).happy           0          .   Happy health probes
VBE.bexxx.xxx_106_68(xxx.xxx.106.68,,82).vcls            1          .   VCL references
VBE.bexxx.xxx_106_68(xxx.xxx.106.68,,82).happy           0          .   Happy health probes
VBE.bexxx.xxx_106_69(xxx.xxx.106.69,,82).vcls            1          .   VCL references
VBE.bexxx.xxx_106_69(xxx.xxx.106.69,,82).happy           0          .   Happy health probes
VBE.bexxx.xxx_106_76(xxx.xxx.106.76,,82).vcls            1          .   VCL references
VBE.bexxx.xxx_106_76(xxx.xxx.106.76,,82).happy           0          .   Happy health probes
VBE.bexxx.xxx_106_78(xxx.xxx.106.78,,82).vcls            1          .   VCL references
VBE.bexxx.xxx_106_78(xxx.xxx.106.78,,82).happy           0          .   Happy health probes

**Comment by unixy** [comment]
This should be fixed in the new release.
